### ISSUE TITLE
Cant go to Class definition

### ISSUE THREAD

**Issue by murataygunn** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#1]
Cant go to Class definition. Allso cant find class methods on Ctrl + T menü. (Goto symbol)
Thanks for the extension.

**Comment by CoffeeChaton** [comment]
I will provide this , before October.

**Comment by CoffeeChaton** [comment]
I provide go to Class def with `topClass` .

the `NestedClass` of `Method()`, just support of  [IntelliSense](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/master/image/Completion_class.gif) now.

```ahk
class topClass {

    class NestedClass {
        class NestedClass2 {

        }
    }

    Method() {
        ;
    }
}```

**Comment by CoffeeChaton** [comment]
But I don't know why `Ctrl + T` is invalid. 
if your `claseName` a combination of English and numbers?
