### ISSUE TITLE
Feature request: Hover function name ballon clickable.

### ISSUE THREAD

**Issue by marius-sucan** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#10]
Hello!

This is awesome. Is it possible to have the hover ballon clickable, for function names/calls?  I do not like pressing F12 , I prefer clicking on the ballon.

Best regards, Marius.

**Comment by CoffeeChaton** [comment]
![img](https://user-images.githubusercontent.com/63182963/213901331-523402f9-eb6c-4c3f-8568-86533e251554.png)

like this?

**Comment by CoffeeChaton** [comment]
good idea!  I can read code with only one hand while I eat breakfast

**Comment by CoffeeChaton** [comment]
https://user-images.githubusercontent.com/63182963/213970546-48582107-1d6a-49fe-86d8-3424ff266a84.mp4

![Snipaste_2023-01-23_13-19-49](https://user-images.githubusercontent.com/63182963/213970630-e6658f44-3d89-4a68-9d74-54ec35970d56.png)

After finishing the light bulb(*mp4*), I found that the right-click menu provides  it....

**Comment by marius-sucan** [comment]
Just keep the light bulb!

**Comment by CoffeeChaton** [comment]
settings.json

```jsonc
{
    "AhkNekoHelp.customize.CodeAction2GotoDefRef": true,
}
```
![img](https://user-images.githubusercontent.com/63182963/214235535-334f568f-d51a-4124-a15b-7a1668d3cc18.png)
