### ISSUE TITLE
Bugs: never used functions are actually used

### ISSUE THREAD

**Issue by marius-sucan** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#17]
Hello!

I have menus that reference functions such as:
`Menu, OpenWithMenu, Add, &Choose external application, browseExternalApp`
... and it says the function is never used. The solution is, make sure that the function is never used by a Menu command.

I also have a gLabel such as:
`Gui, Add, Checkbox, xs+15 y+5 Checked%uiPreferedFileStats% vuiPreferedFileStats gToggleFileStatsDating, &Generate other stats`
... and it says the function is never used. The solution is: for every function name, make sure it is not used with the g prefix somewhere in the document.

It should also not consider as unused the function when i have something like this:
```ahk
value := myFuncNameCall("thisSillyFunc")

myFuncNameCall(func2exec) {
  return %func2exec%()
}

thisSillyFunc() {
   Return 1
}
```
Both functions are used. Here, you can check for every function name, if it is passed as a string, in quotation marks, as in this code. 

Thank you .

Best regards, Marius.

**Comment by CoffeeChaton** [comment]
https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#find-ref-of-function

- [https://www.autohotkey.com/docs/v1/misc/Labels.htm#Functions](https://www.autohotkey.com/docs/v1/misc/Labels.htm#Functions)
    
    > - OK [SetTimer](https://www.autohotkey.com/docs/v1/lib/SetTimer.htm#Functor)
    > - OK [Hotkey](https://www.autohotkey.com/docs/v1/lib/Hotkey.htm#Functor)
    > - ;TODO [Gui events](https://www.autohotkey.com/docs/v1/lib/Gui.htm#Labels) such as GuiClose
    > - ;TODO [Gui control events](https://www.autohotkey.com/docs/v1/lib/Gui.htm#label) (g-labels)
    > - ;TODO [Menu](https://www.autohotkey.com/docs/v1/lib/Menu.htm#Functor)

**Comment by CoffeeChaton** [comment]
```ahk
Menu, MenuName,     Add, MenuItemName                , LabelOrSubmenu
Menu, OpenWithMenu, Add, &Choose external application, browseExternalApp

Gui, Add, Checkbox, xs+15 y+5 Checked%uiPreferedFileStats% vuiPreferedFileStats gToggleFileStatsDating, &Generate other stats
```

- browseExternalApp is LabelOrSubmenu right?
- at `gui ,add` cmd any word `startWtih("g")` is g-label right?

I will fix 2 case at next version.

**Comment by CoffeeChaton** [comment]
```ahk
value := myFuncNameCall("thisSillyFunc") ;---> ref

myFuncNameCall(func2exec) {
    return %func2exec%()
}

thisSillyFunc() { ;--------------------------> def
    Return 1
}
```
I don't understand your question, can you provide more detailed information?
For `thisSillyFunc`, def-ref is indexed

**Comment by marius-sucan** [comment]
> ```ahk
> value := myFuncNameCall("thisSillyFunc") ;---> ref
> 
> myFuncNameCall(func2exec) {
>     return %func2exec%()
> }
> 
> thisSillyFunc() { ;--------------------------> def
>     Return 1
> }
> ```
> I don't understand your question, can you provide more detailed information?
> For `thisSillyFunc`, def-ref is indexed

I tested this and you are right. It seems to work. thisSillyFunc is not listed as unused. 

I'm looking forward to the updated version with menus and gLabel support. I'm cleaning up my project (QPV) with the help of your extension. Thank you for your work. 

Best regards, Marius.

**Comment by CoffeeChaton** [comment]
1. Accidentally closed when operating github, reopened until the next version released 7 days without problems, then closed.
2. In my test environment, except of Gui-event I still understand, the tags/function used by `Menu` `GUI` already provide syntax highlighting and jumping to definitions/references.
3. In the previous version, it was accidentally found that the function name in ahk-v1 matched the label name exactly, I am currently fixing this problem
4. Currently all of my functions, including syntax highlighting, formatting, and jump to references, have problems with the following, I need to think carefully.

```ahk
Hotkey, KeyName
    ,Fn1 ; new line
Hotkey
     , KeyName  ; new line
    ,Fn1 ; new line

SetTimer 
   , fn1
   , 10000

fn1(){
 MsgBox, % "i am fn1"
}
```

![codeOK](https://user-images.githubusercontent.com/63182963/216771771-0020e9e5-cfaa-4044-889d-7c3b7a51bd2b.png)

![codeErr](https://user-images.githubusercontent.com/63182963/216771779-1fd64d7d-bdc6-4afb-a72e-52b68059aea1.png)

**Comment by CoffeeChaton** [comment]
![code](https://user-images.githubusercontent.com/63182963/216772285-d88ac2ab-c9e9-421f-9a33-3e3fd13c0e2e.png)
Current progress (highlighted screenshot in the picture)

Jump to Definition/Reference, because we need to use mp4, the file is too big to upload.

**Comment by marius-sucan** [comment]
Thank you for the work you are doing.

**Comment by CoffeeChaton** [comment]
- v0.0.21 Published, awaiting Microsoft's automated review system.

- v0.0.22 will fix:  
> - Sort F-flag `Sort, MyVar, F IntegerSort D` <https://www.autohotkey.com/docs/v1/lib/Sort.htm#Options>
> - <https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/issues/17#issuecomment-1416761073>

else
```ahk
    ;NOT plan to support-----------------------
    ;https://www.autohotkey.com/docs/v1/Objects.htm#Function_References
    RetVal := %Func%(Params) ; Requires [v1.1.07+]
    RetVal := Func.Call(Params) ; Requires [v1.1.19+]
    RetVal := Func.(Params) ; Not recommended

    ;https://www.autohotkey.com/docs/v1/misc/RegExCallout.htm#callout-functions
    RegExMatch(Haystack, "i)(The) (\w+)\b(?CCallout)")
    ;                                         ^Callout

    ;https://www.autohotkey.com/docs/v1/Variables.htm#ref
    cc := fn%i%() ;
```

**Comment by marius-sucan** [comment]
It seems to be working fine in v0.0.21. Thank you <3

I closed the issue.
