### ISSUE TITLE
Incorrect ballon message on hover

### ISSUE THREAD

**Issue by marius-sucan** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#21]
Hello!

I updated the extension... v.0.0.21

I have this:

   ` Gui, Add, Button, x+1 hp w25 gStartPickingColor vPickuFillBehindColor +hwndhTemp, P `

When I hover the gLabel or vVar, I get a ballon saying: "unknown text of PanelFillBehind()". I get the same for Add, Button texts. For Gui, it shows the documnetation for the Gui command.

Best regards, Marius.

**Comment by CoffeeChaton** [comment]
- `vVar` : I know vVar is variable, but this is as expected because I haven't figured out how to parse.
- gLabel :I forgot to handle HoverProvider but it's not hard.

**Comment by marius-sucan** [comment]
When I hover Add, it should say «Param1 for Gui command, hover Gui for more details»

When I hover Button, it should say «Param2 for Gui command, hover Gui for more details».

When I hover vVarName, it should say «The variable associated with the Gui control». If it is not declared, it should say: "ERROR: The variable must be declared as global or static.".

When I hover gLabel, it should say «The label or function associated with the Gui control». And if it is nowhere declared: It should also say: "ERROR: The reference is undeclared".

Best regards, Marius.

**Comment by CoffeeChaton** [comment]
![RAW1](https://user-images.githubusercontent.com/63182963/217010416-387c7b80-636a-4155-b3cb-36b9bff1fbf5.gif)

**Comment by marius-sucan** [comment]
![image](https://user-images.githubusercontent.com/35074874/217065444-b1354bdf-22e3-4ca1-a27d-9df3575ede31.png)

**Comment by CoffeeChaton** [comment]
This is a preview screen, the new version has not been released, I want to fix `Menu` `Hotkey`  `SetTimer`  Hover together and then release the version, ... I thought [0335af](0335af53f9bc60a5509383665b590a28a151a984) would be automatically attached under this one.

**Comment by CoffeeChaton** [comment]
> `Gui, Add, Button, x+1 hp w25 gStartPickingColor vPickuFillBehindColor +hwndhTemp, P`

```ahk
GUI, Add, Button, x+1 hp w25 gStartPickingColor vPickuFillBehindColor +hwndhTemp, P
;                             ^ g-func https://www.autohotkey.com/docs/v1/lib/GuiControls.htm#Text
;                                                 ^ v-var https://www.autohotkey.com/docs/v1/lib/Gui.htm#Events
;                                                                           ^ hwnd-var Hwnd OutputVar [v1.1.04+]  https://www.autohotkey.com/docs/v1/lib/Gui.htm#Options
```

add support at 0.0.23(2023-02-17)

> ....«Param2 for Gui command, hover Gui for more details»...

In this part, human parsing parameters will be faster than programs. At the same time, I will greatly correct the parsing commands and residual text strings in version 0.1.0, so I will not change them for the time being.

> When I hover gLabel, it should say «The label or function associated with the Gui control». And if it is nowhere declared: It should also say: "ERROR: The reference is undeclared".

when ahk-v1 run,it would immediately warn ,the called function/label is not defined, unless the prompt in this part of ahk is not convenient enough, I don’t want to repeat the wheel

**Comment by CoffeeChaton** [comment]
Expected to close in 7 days

**Comment by marius-sucan** [comment]
I tested 0.0.23(2023-02-17) and now it is much better. Thank you for the work.

Best regards, Marius.
