### ISSUE TITLE
Unexplained nag message about workspaces, with grammatical errors

### ISSUE THREAD

**Issue by Lexikos** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#5]
When the extension loads in a window with no workspace, the following popup notification is shown:

> pleas using workspaces!

I have a few objections to this:
  - There is no explanation for why you are suggesting this.
  - I think it is not appropriate for a language extension to be telling me how to use VS Code in general.
  - I have specific reasons for opening a window without a workspace (relating to other problems with the extension, actually).
  - There are as many grammatical errors in the message as there are words.

*Please use workspaces.*

Please remove this notice. If there is some functionality of the extension that doesn't work without a workspace, you could display a notice about which function will not work; but I would advise against doing that if the function is non-essential.

**Comment by CoffeeChaton** [comment]
> There is no explanation for why you are suggesting this.

Leftovers, now useless, I will remove this at weekend

> I think it is not appropriate for a language extension to be telling me how to use VS Code in general.

You are right.

> If there is some functionality of the extension that doesn't work without a workspace, you could display a notice about which function will not work

I will check that those functions are definitely needed to work the area

**Comment by CoffeeChaton** [comment]
fix it at v0.0.15
