### ISSUE TITLE
Can't figure out how to disable linters globally

### ISSUE THREAD

**Issue by ARTIFICIAL-CODE** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#7]
I love the extension, but sometimes I just want to work on a file without it being linted

**Comment by ARTIFICIAL-CODE** [comment]
Sorry, I had a weird GitHub theme that showed open issues in red, didn't notice Lexikos post.
I fully agree with him, but I'm grateful that the extension pointed out that some of my code were using deprecated things.
Going to close this issue and look into doing things the correct way.

**Comment by CoffeeChaton** [comment]
i provided some config at v0.0.15(2022-11-20) .

Thank of your love!

```jsonc
// settings.json // https://stackoverflow.com/questions/65908987/how-can-i-open-visual-studio-codes-settings-json-file
{
    "AhkNekoHelp.Diag.AMasterSwitch": "auto",
    "AhkNekoHelp.Diag.code107LegacyAssignment": true,
    "AhkNekoHelp.Diag.code300FuncSize": 100,
    "AhkNekoHelp.Diag.code800Deprecated": true
}
```
