### ISSUE TITLE
Not sure how to detect if working

### ISSUE THREAD

**Issue by LeeTimms** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#8]
Hi I'm a Newbie to autohotkey and vscode and i am hot sure how to determine if Neko is working or not. Is there some way of testing this extension specifically?

**Comment by CoffeeChaton** [comment]
![Snipaste](https://user-images.githubusercontent.com/63182963/209655889-dc8bdb56-74ec-4a76-8c34-10e21e8b106e.jpg)

if extension activation, vscode will show "activation time" like image
else may be is [activationEvents](https://code.visualstudio.com/api/references/activation-events) not match
1. not open any [_.ahk_](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/master/package.json#L227) file.
2. enabled [AutoHotkey v2 Language Support](https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp) and it think the file is ahk v2 and auto change file to "AutoHotKey2".
3. unexpected error crash , [open console](https://stackoverflow.com/questions/62890841/in-vs-code-is-it-possible-to-programmatically-open-devtools) to debug.

**Comment by CoffeeChaton** [comment]
![img](https://user-images.githubusercontent.com/63182963/214236290-7ce804be-4388-48ba-a65e-8aaa148a6926.png)

I add log at v0.0.19(2023-01-24)
