### ISSUE TITLE
Any thoughts about including a debugger?

### ISSUE THREAD

**Issue by murataygunn** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#9]
Any thoughts about including a debugger?

**Comment by CoffeeChaton** [comment]
No, I have no interest and time to maintain it.
[This](https://github.com/CoffeeChaton/ahkDebug) is a legacy code based on [autohotkey-plus (2020-04)](https://github.com/vscode-autohotkey/autohotkey-plus) with some small fix. 
Except for the format, just fix safe null value check, but [DAP](https://microsoft.github.io/debug-adapter-protocol/) has too many cases, and it is too complicated to trigger, so I have no maintenance. 
Now I use [AutoHotKey Debug](https://marketplace.visualstudio.com/items?itemName=helsmy.autohotkey-debug).

**Comment by CoffeeChaton** [comment]
add suggest [AutoHotKey Debug](https://marketplace.visualstudio.com/items?itemName=helsmy.autohotkey-debug) at README

**Comment by CoffeeChaton** [comment]
close with not plan
